name: Hotfix PR to Develop

on:
  pull_request:
    types:
      - closed
    branches:
      - 'production'

jobs:
  create_pr:
    if: startsWith(github.event.pull_request.head.ref, 'hotfix/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.event.pull_request.head.ref }}"
          destination_branch: "develop"
          pr_title: "Merge hotfix into develop: ${{ github.event.pull_request.head.ref }}"
          pr_body: "This PR merges the hotfix ${{ github.event.pull_request.head.ref }} into develop."
          github_token: ${{ secrets.GITHUB_TOKEN }}
